name: snafu
description: Snafu replica for Flame 6th anniversary.
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flame: ^1.10.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.1.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

