name: snafu
description: Snafu replica for Flame 6th anniversary.
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.10.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flame_lint: ^1.1.1

flutter:
  uses-material-design: true

